### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith' for ambiguous sequence

### ISSUE THREAD

**Issue by phyden** [cov-lineages/pangolin#510] opened 2023-02-23 10:10 UTC
Hi.

It looks like the output behaviour of the new model changed in case a sequence contains only Ns which causes this error:
```
  Traceback (most recent call last):
    File "/opt/conda/bin/pangolin", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/pangolin/command.py", line 240, in main
      generate_final_report(preprocessing_csv, inference_csv, cached_csv, config[KEY_ALIAS_FILE], constellation_list, config[KEY_PANGOLIN_DATA_VERSION],config[KEY_ANALYSIS_MODE], args.skip_designation_cache, config[KEY_OUTFILE],config)
    File "/opt/conda/lib/python3.8/site-packages/pangolin/utils/report_collation.py", line 248, in generate_final_report
      not expanded_pango_lineage.startswith(expanded_scorpio_lineage) and \
  AttributeError: 'NoneType' object has no attribute 'startswith'
```
The versions where I encountered this error were:
```
pangolin: 4.2
pangolin-data: 1.18.1
constellations: v0.1.10
scorpio: 0.3.17
usher 0.6.2
gofasta 1.2.0
minimap2 2.24-r1122
faToVcf: 426
```

while this setting did not stumble over my sequence:
```
pangolin: 4.2
pangolin-data: 1.18
constellations: v0.1.10
scorpio: 0.3.17
usher 0.6.2
gofasta 1.1.0
minimap2 2.24-r1122
faToVcf: 426
```

Here's the "sequence" of my example:
[empty_sequence.fasta.gz](https://github.com/cov-lineages/pangolin/files/10812422/empty_sequence.fasta.gz)

Edit: looking at the versions now, it might also be that the change in "gofasta" version causes the problem though.

**Comment by phyden** [comment] 2023-02-23 10:32
Hi again,

I just tested with setting 
```
pangolin: 4.2
pangolin-data: 1.18.1
constellations: v0.1.10
scorpio: 0.3.17
usher 0.6.2
gofasta 1.1.0
minimap2 2.24-r1122
faToVcf: 426
```
and get no error, so the problem must be gofasta 1.2.0

**Comment by arodzh-sudo** [comment] 2023-02-23 15:48
Hi @phyden, my settings are basically the same as you with the only difference being scorpio=0.3.18 and I'm still encountering the same error

```
pangolin: 4.2
pangolin-data: 1.18.1
constellations: v0.1.10
scorpio: 0.3.18
usher 0.6.2
gofasta 1.1.0
minimap2 2.24-r1122
faToVcf: 426
```

**Comment by AngieHinrichs** [comment] 2023-02-23 17:32
Thanks for reporting this @phyden .  I tried to reproduce the error by doing a `mamba update gofasta` (which updated gofasta to 1.2.0) and running pangolin on your empty_sequence.fasta.gz but I didn't get the error, so there must be some other hidden dependency problem.  pangolin depends on a lot of conda (and pip) packages besides what we show in `pangolin --all-versions`.  This is what I get from `pangolin --all-versions` now:
```
pangolin: 4.2
pangolin-data: 1.18.1
constellations: v0.1.10
scorpio: 0.3.17
usher 0.6.2
gofasta 1.2.0
minimap2 2.24-r1122
faToVcf: 426
```

but that's not the whole story.  What method did you use to update pangolin?  Can you make a file showing all package versions in your pangolin environment using this command:
```
conda list > pangolin-510-phyden-env.txt
```
and attach the file to this issue?  Then I can compare that with mine (or just make a new env with the same versions) and hopefully reproduce & fix the problem.

**Comment by wm75** [comment] 2023-02-23 17:49
@phyden what's really weird about your error is that this is the complete line of code that's mentioned in your traceback:
https://github.com/cov-lineages/pangolin/blob/b0367c5a119ce462f56a6c3d74c75c2f8005fee7/pangolin/utils/report_collation.py#L247-L249

which means that basically what you're seeing should be impossible to happen.

So just to make sure your pangolin code is what it claims to be, could you also check your code in `/opt/conda/lib/python3.8/site-packages/pangolin/utils/report_collation.py` to see if it looks like it should?

**Comment by wm75** [comment] 2023-02-23 17:52
@phyden strike my previous comment. Obviously I was misreading the code.

**Comment by fischer-hub** [comment] 2023-02-23 19:51
Hi, I'm facing the same issue. Since I reinstalled pangolin and pangolin-data using conda I get `  AttributeError: 'NoneType' object has no attribute 'startswith'`  on some sequences. Since Im using fasta files containing multiple sequences as input I'm not quite sure yet which sequences cause the issue.

I tried @phyden s fix but sadly its still crashing for me with the same error with gofasta 1.1.0 installed..

I attached the environment file in which pangolin was run I hope that helps maybe !
Since we are using pangolin as part of a nextflow pipeline we have to use the attatched environment file to install and run pangolin.
[pangolin.yaml.txt](https://github.com/cov-lineages/pangolin/files/10817794/pangolin.yaml.txt) (had to rename because of github file type restrictions)

**Comment by arodzh-sudo** [comment] 2023-02-23 19:54
Hi @AngieHinrichs,

I'm encountering the same error. I also tried @phyden fix but it didn't work. 

My settings are the following:

```
pangolin: 4.2
pangolin-data: 1.18.1
constellations: v0.1.10
scorpio: 0.3.18
usher 0.6.2
gofasta 1.2.0
minimap2 2.24-r1122
faToVcf: 426
```

Here's the output of the conda list > pangolin-510-phyden-env.txt command:
```

# packages in environment at /home/arodzh/miniconda3/envs/pangolin:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
amply                     0.1.5              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
biopython                 1.81             py38h1de0b5d_0    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
brotlipy                  0.7.0           py38h0a891b7_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38h4a40e3a_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
coin-or-cbc               2.10.8               h3786ebc_0    conda-forge
coin-or-cgl               0.60.6               h6f57e76_2    conda-forge
coin-or-clp               1.17.7               hc56784d_2    conda-forge
coin-or-osi               0.108.7              h2720bb7_2    conda-forge
coin-or-utils             2.11.6               h202d8b1_2    conda-forge
coincbc                   2.10.8            0_metapackage    conda-forge
configargparse            1.5.3              pyhd8ed1ab_0    conda-forge
connection_pool           0.0.3              pyhd3deb0d_0    conda-forge
constellations            0.1.10                   pypi_0    pypi
cryptography              39.0.0           py38h1724139_0    conda-forge
datrie                    0.8.2            py38h0a891b7_6    conda-forge
docutils                  0.19             py38h578d9bd_1    conda-forge
filelock                  3.9.0              pyhd8ed1ab_0    conda-forge
git-lfs                   3.3.0                ha770c72_0    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.31             pyhd8ed1ab_0    conda-forge
gofasta                   1.2.0                h9ee0642_0    bioconda
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0              pyha770c72_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
isa-l                     2.30.0               ha770c72_4    conda-forge
joblib                    1.2.0                    pypi_0    pypi
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_core              5.2.0            py38h578d9bd_0    conda-forge
k8                        0.2.5                hd03093a_2    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcbor                   0.9.0                h9c3ff4c_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libfido2                  1.11.0               h727a467_0    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
liblapacke                3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               3.20.2               h6239696_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libudev1                  252                  h166bdaf_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
mafft                     7.515                hec16e2b_0    bioconda
minimap2                  2.24                 h7132678_1    bioconda
mpi                       1.0                     openmpi    conda-forge
mysql-connector-c         6.1.11            h6eb9d5d_1007    conda-forge
nbformat                  5.7.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.24.2           py38h10c12cc_0    conda-forge
openmpi                   4.1.2                hbfc84c5_0    conda-forge
openssh                   9.1p1                h2baec63_1    conda-forge
openssl                   1.1.1t               h0b41bf4_0    conda-forge
pandas                    1.5.3                    pypi_0    pypi
pangolin                  4.2                      pypi_0    pypi
pangolin-data             1.18.1                   pypi_0    pypi
pip                       19.3.1                   py38_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.0.0              pyhd8ed1ab_0    conda-forge
psutil                    5.9.4            py38h0a891b7_0    conda-forge
pulp                      2.7.0            py38h578d9bd_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3           py38h1de0b5d_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.15          h257c98d_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytz                      2022.7.1                 pypi_0    pypi
pyyaml                    6.0              py38h0a891b7_5    conda-forge
ratelimiter               1.2.0           pyhd8ed1ab_1003    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
scikit-learn              1.2.1                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
scorpio                   0.3.18                   pypi_0    pypi
setuptools                67.4.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
smart_open                6.3.0              pyhd8ed1ab_1    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snakemake-minimal         6.8.0              pyhdfd78af_0    bioconda
stopit                    1.1.2                      py_0    conda-forge
tabulate                  0.8.10                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
toposort                  1.9                pyhd8ed1ab_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
ucsc-fatovcf              426                  h954228d_0    bioconda
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
usher                     0.6.2                h99b1ad8_0    bioconda
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1           py38h0a891b7_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.14.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

**Comment by EricFournier3** [comment] 2023-02-23 20:51
Hi, same issue for me today with pangolin-data: 1.18.1

(pangolin) [foueri01@inspq.qc.ca@slurm10p 20230223]$ pangolin --all-versions
pangolin: 4.2
pangolin-data: 1.18.1
constellations: v0.1.10
scorpio: 0.3.17
usher 0.5.4
gofasta 1.0.0
minimap2 2.24-r1122
faToVcf: 426

**Comment by EricFournier3** [comment] 2023-02-23 21:00
I get the error when I run on L00586670_L00586816.fasta (two sequences), but not with L00586816.fasta (one sequence), L00586670.fasta (one sequence) and  L00586816_L00586670.fasta (reverse order of  L00586670_L00586816.fasta)

 pangolin -t 4 --analysis-mode usher  --max-ambig 0.3 --outfile res_L00586670_L00586816.csv L00586670_L00586816.fasta

**Comment by phyden** [comment] 2023-02-23 21:42
Hi, sorry for the confusion.. I thought it would be easy to fix with downgrading gofasta, but apparently my pipeline also crashed again with the same error.
We are using podman images, so I can't simply update the data only, to update to a newer version I need to rebuild the entire thing, which I did. And after downgrading gofasta I tried to feed the single sequence that failed in the entire batch previously did not show this error anymore. So I thought this might be a solution..

However, now I re-tried with my old image and the error also occurs on the same multi-fasta input file containing 94 sequences after typing `pangolin --update-data`. So I believe that the problem is somehow linked to the usher model update.

**Comment by AngieHinrichs** [comment] 2023-02-24 00:22
Thanks so much for the input, everyone!  I was able to reproduce the problem with a sequence assigned to a new lineage in v1.18.1.  I think the cause is a problem pointed out by @OnePotato2 in #35: I updated lineageTree.pb but did not update the file alias_key.json (and lineages.hash.csv) that @aineniamh has been updating along with the pangoLEARN model.  So the alias_key.json in v1.18.1 is out of date relative to lineageTree.pb and we get this new error.  

I just updated pangolin-data (and pangolin-assignment) to v1.18.1.1 with an updated alias_key.json and lineages.hash.csv, so please try `pangolin --update-data` (or whatever method you use to update pangolin-data to the latest available version).  When I run pangolin on the same new-lineage sequence with pangolin-data v1.18.1.1 (not v1.18.1), it works.

I didn't detect this problem before release because I run pangolin with the new lineageTree.pb on all sequences with `--skip-scorpio` in order to produce the cache file for the pangolin-assignment repository, and `--skip-scorpio` bypasses the part of the code that has the error when alias_key.json is out of date.

**Comment by AngieHinrichs** [comment] 2023-02-24 00:56
@EricFournier3 thank you for the sequence files.  I was a little alarmed that you would get different results by changing the order of the sequences in the file, but I think the sequences are different (the second file has L00586681 not L00586816):
```
grep '^>' L00586670_L00586816.fasta
>Canada/Qc-L00586670001/2023
>Canada/Qc-L00586816001/2023

grep '^>' L00586816_L00586670.fasta
>Canada/Qc-L00586670001/2023
>Canada/Qc-L00586681001/2023
```
Canada/Qc-L00586816001/2023 is assigned to new lineage DV.1, triggering the error with pangolin-data v1.18.1's out-of-date alias_key.json file.  But with pangolin-data v1.18.1.1, it works.

**Comment by AlaaALatif** [comment] 2023-02-24 00:57
Hi all, I ran into the same issue last night, and following @AngieHinrichs instruction to run `pangolin --update-data` fixed it for me. I validated it by running it against 31415 sequences that were randomly sampled from GISAID. 

Thank you for sharing useful information about the issue and how to resolve it. 

```
pangolin: 4.2
pangolin-data: 1.18.1.1
constellations: v0.1.10
scorpio: 0.3.18
usher 0.6.2
gofasta 1.2.0
minimap2 2.24-r1122
faToVcf: 426
```

**Comment by EricFournier3** [comment] 2023-02-24 01:22
> @EricFournier3 thank you for the sequence files. I was a little alarmed that you would get different results by changing the order of the sequences in the file, but I think the sequences are different (the second file has L00586681 not L00586816):
> 
> ```
> grep '^>' L00586670_L00586816.fasta
> >Canada/Qc-L00586670001/2023
> >Canada/Qc-L00586816001/2023
> 
> grep '^>' L00586816_L00586670.fasta
> >Canada/Qc-L00586670001/2023
> >Canada/Qc-L00586681001/2023
> ```
> 
> Canada/Qc-L00586816001/2023 is assigned to new lineage DV.1, triggering the error with pangolin-data v1.18.1's out-of-date alias_key.json file. But with pangolin-data v1.18.1.1, it works.

Thank you @AngieHinrichs . Sorry for this confusion

**Comment by EricFournier3** [comment] 2023-02-24 01:35
@AngieHinrichs  its working correctly now with  pangolin-data v1.18.1.1. Thank you again @AngieHinrichs for this quick fix

**Comment by AngieHinrichs** [comment] 2023-02-24 03:38
Thanks so much @AlaaALatif and @EricFournier3 for confirming the fix!  I will close this issue but please let us know if you find any other problems.

**Closed by AngieHinrichs** 2023-02-24 03:38 UTC
